### ISSUE TITLE
Migrating Table Storage to Cosmos Db Table API

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure-Samples/azure-cosmos-db-table-dotnet-getting-started#3]
Are there any tools available to migrate Azure Table storage to Cosmos DB to access using Table APIs? I found `Data Migration Tool` but it only supports Cosmos db Tables access through Document API.

**Comment by isamllr** [comment]
Please check https://datamigration.microsoft.com/scenario/azuretable-to-cosmos

**Comment by yaronyg** [comment]
@prabhakarreddy1234 please feel free to re-open the issue if the previous link didn't resolve your question.
