### ISSUE TITLE
Retire this repo in favour of https://github.com/Azure-Samples/storage-table-dotnet-getting-started

### ISSUE THREAD

**Issue by SeanFeldman** [Azure-Samples/azure-cosmos-db-table-dotnet-getting-started#6]
This sample is old (using non-GAed library) and should be retired in favour of [another sample](https://github.com/Azure-Samples/storage-table-dotnet-getting-started).

[Documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet#clone-the-sample-application) should be also update **not** to reference this sample

**Comment by yaronyg** [comment]
Yup, the docs are changed. However I do plan on pushing an update to this to move it to the SDK. Please re-open this issue if I didn't fully address your concerns.

**Comment by SeanFeldman** [comment]
👍
