### ISSUE TITLE
MethodAccessException: Attempt by method 

### ISSUE THREAD

**Issue by wpitallo** [Azure-Samples/azure-cosmos-db-table-dotnet-getting-started#8]
Hi I am not sure where to get help with cosmos issues. 

There seems to be an issue when trying to initilize an inherited Table 

using Microsoft.Azure.CosmosDB.Table;
using Server.Base.Azure.Table.Adapters;
using Microsoft.Azure.Storage.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Server.Base.Azure.Table.Models
{
    public class CosmosDbBase : TableEntity
  
    {

        public string TableName { get; }
        public CloudTable Table { get; }

        public CosmosDbBase() --> Fails here: 
        {
            var i = 0;
        }
  }
}

I get the following error when trying to construct the class:

MethodAccessException: Attempt by method 'Microsoft.Azure.CosmosDB.Table.TableEntity.set_DisableCompiledSerializers(Boolean)' to access method 'Microsoft.Azure.Storage.Core.Util.PlatformAgnosticReflectionExtensions.FindStaticMethods(System.Type, System.String)' failed.

I can do the exact same thing with table storage and everything works perfectly, any ideas whats causing this?

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Azure.CosmosDB.Table.TableEntity' threw an exception.
  Source=Microsoft.Azure.CosmosDB.Table
 
Inner Exception 1:
MethodAccessException: Attempt by method 'Microsoft.Azure.CosmosDB.Table.TableEntity.set_DisableCompiledSerializers(Boolean)' to access method 'Microsoft.Azure.Storage.Core.Util.PlatformAgnosticReflectionExtensions.FindStaticMethods(System.Type, System.String)' failed.

**Comment by conniey** [comment]
@wpitallo I got this error when I was trying to a .NET Core application with the .NET Framework NuGet packages for Cosmos DB (Table APIs)... It does not look like the Microsoft.Azure.CosmosDB.Table has been migrated to .NET Core, yet

**Comment by firemanwayne** [comment]
I am receiving the same error using .NetCore 2.0.6. I've been searching everwhere and your post is the first hint at the issue and, sadly, I'm relieved that it's not just me.

**Comment by MisinformedDNA** [comment]
I'm also targetting .NET Core. All Azure libraries should be targeting .NET Standard 2.0 at this point.

**Comment by MatthewSteeples** [comment]
Also seeing this issue targeting NETSTANDARD20 running under VS2019 RC

**Comment by MisinformedDNA** [comment]
There is now a .NET Standard implementation of [Cosmos](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table). Is this still an issue? Or can it be closed?

**Comment by wpitallo** [comment]
Have not had a chance to test this again, but will close it anyway. Can re-open it if anyone still receives the error.
